import { GameMetadata } from './types';

export const GAMES: GameMetadata[] = [
  {
    id: 'snake',
    title: 'Snake',
    description: 'Classic snake game. Eat the food to grow longer!',
    icon: 'Snake',
    category: 'Arcade',
    difficulty: 'Easy',
  },
  {
    id: 'tictactoe',
    title: 'Tic Tac Toe',
    description: 'The classic game of X and O.',
    icon: 'Grid3X3',
    category: 'Logic',
    difficulty: 'Easy',
  },
  {
    id: 'memory',
    title: 'Memory Match',
    description: 'Find all the matching pairs of cards.',
    icon: 'Brain',
    category: 'Puzzle',
    difficulty: 'Medium',
  },
  {
    id: 'minesweeper',
    title: 'Minesweeper',
    description: 'Clear the board without hitting any mines.',
    icon: 'Bomb',
    category: 'Puzzle',
    difficulty: 'Hard',
  },
  {
    id: 'tetris',
    title: 'Tetris',
    description: 'Stack the blocks and clear the lines.',
    icon: 'Square',
    category: 'Arcade',
    difficulty: 'Hard',
  },
  {
    id: '2048',
    title: '2048',
    description: 'Join the numbers to get to the 2048 tile!',
    icon: 'Hash',
    category: 'Puzzle',
    difficulty: 'Medium',
  },
  {
    id: 'sudoku',
    title: 'Sudoku',
    description: 'Fill the grid with numbers 1-9.',
    icon: 'Table',
    category: 'Logic',
    difficulty: 'Hard',
  },
  {
    id: 'hangman',
    title: 'Hangman',
    description: 'Guess the word before the man is hanged.',
    icon: 'Type',
    category: 'Puzzle',
    difficulty: 'Medium',
  },
  {
    id: 'whackamole',
    title: 'Whack-a-Mole',
    description: 'Hit the moles as they pop up!',
    icon: 'Zap',
    category: 'Arcade',
    difficulty: 'Easy',
  },
  {
    id: 'breakout',
    title: 'Breakout',
    description: 'Destroy all the bricks with the ball.',
    icon: 'Layout',
    category: 'Arcade',
    difficulty: 'Medium',
  },
  {
    id: 'pong',
    title: 'Pong',
    description: 'Classic table tennis game.',
    icon: 'Activity',
    category: 'Arcade',
    difficulty: 'Easy',
  },
  {
    id: 'flappy',
    title: 'Flappy Bird',
    description: 'Fly through the pipes without hitting them.',
    icon: 'Bird',
    category: 'Arcade',
    difficulty: 'Hard',
  },
  {
    id: 'wordle',
    title: 'Wordle',
    description: 'Guess the 5-letter word in 6 tries.',
    icon: 'MessageSquare',
    category: 'Puzzle',
    difficulty: 'Medium',
  },
  {
    id: 'dino',
    title: 'Dino Run',
    description: 'Jump over obstacles as a running dinosaur.',
    icon: 'Footprints',
    category: 'Arcade',
    difficulty: 'Easy',
  },
  {
    id: 'simon',
    title: 'Simon Says',
    description: 'Repeat the sequence of colors and sounds.',
    icon: 'Music',
    category: 'Memory',
    difficulty: 'Medium',
  } as any,
  {
    id: 'tower',
    title: 'Tower Blocks',
    description: 'Stack blocks as high as you can.',
    icon: 'Layers',
    category: 'Arcade',
    difficulty: 'Medium',
  }
];
